createNamespace: true

prometheus:
  enabled: true
  server:
    persistentVolume:
      enabled: true
      size: 10Gi
    service:
      type: NodePort
      nodePort: 30090
    extraScrapeConfigs: |
      - job_name: 'sockshop'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: "true"
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: "(.+)"
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: "(.+):(?:\\d+);(\\d+)"
            replacement: "$1:$2"
            target_label: __address__

grafana:
  enabled: true
  adminUser: admin
  adminPassword: Myfutursecret
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://prometheus-stack-kube-prom-prometheus.monitoring.svc.cluster.local:9090
          isDefault: true
  persistence:
    enabled: true
    size: 5Gi
  service:
    type: NodePort
    nodePort: 30300